const CartActionTypes = {
  SET_CART: 'SET_CART',
  TOGGLE_CART_HIDDEN: 'TOGGLE_CART_HIDDEN',
  ADD_PRODUCT: 'ADD_PRODUCT',
  REMOVE_PRODUCT: 'REMOVE_PRODUCT',
  CLEAR_PRODUCT_FROM_CART: 'CLEAR_PRODUCT_FROM_CART',
  CLEAR_CART: 'CLEAR_CART'
}

export default CartActionTypes