const ProductsActionTypes = {
  FETCHING_START: 'FETCHING_START',
  FETCHING_FAILED: 'FETCHING_FAILED',
  FETCH_ALL_PRODUCTS_SUCCESS: 'FETCH_ALL_PRODUCTS',
  FETCH_SINGLE_COLLECTION_PRODUCTS_SUCCESS: 'FETCH_SINGLE_COLLECTION_PRODUCTS_SUCCESS',
  FETCH_PRODUCT_SUCCESS: 'FETCH_PRODUCT_SUCCESS',
  ADD_PRODUCTS: 'ADD_PRODUCTS',
  EDIT_PRODUCT: 'EDIT_PRODUCT'
}

export default ProductsActionTypes