const ProductsActionTypes = {
  FETCH_ALL_PRODUCTS_REQUESTED: 'FETCH_ALL_PRODUCTS_REQUESTED',
  FETCH_ALL_PRODUCTS_SUCCESS: 'FETCH_ALL_PRODUCTS_SUCCESS',

  FETCH_PRODUCT_REQUESTED: 'FETCH_PRODUCT_REQUESTED',
  FETCH_PRODUCT_FOR_EDIT_REQUESTED: 'FETCH_PRODUCT_FOR_EDIT_REQUESTED',
  FETCH_PRODUCT_SUCCESS: 'FETCH_PRODUCT_SUCCESS',

  FETCH_SINGLE_COLLECTION_PRODUCTS_REQUESTED: 'FETCH_SINGLE_COLLECTION_PRODUCTS_REQUESTED',
  FETCH_SINGLE_COLLECTION_PRODUCTS_SUCCESS: 'FETCH_SINGLE_COLLECTION_PRODUCTS_SUCCESS',

  FETCHING_FAILED: 'FETCHING_FAILED',

  CREATE_PRODUCT_REQUESTED: 'CREATE_PRODUCT_REQUESTED',
  CREATE_PRODUCT_FAILED: 'CREATE_PRODUCT_FAILED',

  EDIT_PRODUCT_REQUESTED: 'EDIT_PRODUCT_REQUESTED',
  EDIT_PRODUCT_SUCCESS: 'EDIT_PRODUCT_SUCCESS',
  EDIT_PRODUCT_FAILED: 'EDIT_PRODUCT_FAILED', 
}

export default ProductsActionTypes