const ProductsActionTypes = {
  FETCH_ALL_PRODUCTS_REQUESTED: 'FETCH_ALL_PRODUCTS_REQUESTED',
  FETCH_ALL_PRODUCTS_SUCCESS: 'FETCH_ALL_PRODUCTS_SUCCESS',

  FETCH_PRODUCT_REQUESTED: 'FETCH_PRODUCT_REQUESTED',
  FETCH_PRODUCT_FOR_EDIT_REQUESTED: 'FETCH_PRODUCT_FOR_EDIT_REQUESTED',
  FETCH_PRODUCT_SUCCESS: 'FETCH_PRODUCT_SUCCESS',

  FETCH_SINGLE_COLLECTION_PRODUCTS_REQUESTED: 'FETCH_SINGLE_COLLECTION_PRODUCTS_REQUESTED',
  FETCH_SINGLE_COLLECTION_PRODUCTS_SUCCESS: 'FETCH_SINGLE_COLLECTION_PRODUCTS_SUCCESS',

  FETCHING_FAILED: 'FETCHING_FAILED',

  CREATE_PRODUCT_REQUESTED: 'CREATE_PRODUCT_REQUESTED',
  CREATE_PRODUCT_FAILED: 'CREATE_PRODUCT_FAILED',

  EDIT_PRODUCT_REQUESTED: 'EDIT_PRODUCT_REQUESTED',
  EDIT_PRODUCT_SUCCESS: 'EDIT_PRODUCT_SUCCESS',
  EDIT_PRODUCT_FAILED: 'EDIT_PRODUCT_FAILED', 

  // ADD_ADDITIONAL_IMAGE_TO_PRODUCT_REQUESTED: 'ADD_ADDITIONAL_IMAGE_TO_PRODUCT_REQUESTED',
  // ADD_ADDITIONAL_IMAGE_TO_PRODUCT_SUCCESS: 'ADD_ADDITIONAL_IMAGE_TO_PRODUCT_SUCCESS',
  // ADD_ADDITIONAL_IMAGE_TO_PRODUCT_FAILED: 'ADD_ADDITIONAL_IMAGE_TO_PRODUCT_FAILED',

  // ADD_COLOR_AND_IMAGES_TO_PRODUCT_REQUESTED: 'ADD_COLOR_AND_IMAGES_TO_PRODUCT_REQUESTED',

  ADD_COLOR_TO_PRODUCT_REQUESTED: 'ADD_COLOR_DATA_TO_PRODUCT_REQUESTED',
  ADD_COLOR_TO_PRODUCT_SUCCESS: 'ADD_COLOR_DATA_TO_PRODUCT_SUCCESS',
  ADD_COLOR_TO_PRODUCT_FAILED: 'ADD_COLOR_DATA_TO_PRODUCT_FAILED',

  EDIT_PRODUCT_COLOR_DATA_REQUESTED: 'EDIT_PRODUCT_COLOR_DATA_REQUESTED',
  EDIT_PRODUCT_COLOR_DATA_SUCCESS: 'EDIT_PRODUCT_COLOR_DATA_SUCCESS',
  EDIT_PRODUCT_COLOR_DATA_FAILED: 'EDIT_PRODUCT_COLOR_DATA_FAILED',

  // DELETE_ONE_IMAGE_FROM_COLOR_IMAGES_REQUESTED: 'DELETE_ONE_IMAGE_FROM_COLOR_IMAGES_REQUESTED',
  // DELETE_ONE_IMAGE_FROM_COLOR_IMAGES_SUCCESS: 'DELETE_ONE_IMAGE_FROM_COLOR_IMAGES_SUCCESS',
  // DELETE_ONE_IMAGE_FROM_COLOR_IMAGES_FAILED: 'DELETE_ONE_IMAGE_FROM_COLOR_IMAGES_FAILED',

  REMOVE_ONE_IMAGE_FROM_COLOR_IMAGES_REQUESTED: 'REMOVE_ONE_IMAGE_FROM_COLOR_IMAGES_REQUESTED',
  REMOVE_ONE_IMAGE_FROM_COLOR_IMAGES_SUCCESS: 'REMOVE_ONE_IMAGE_FROM_COLOR_IMAGES_SUCCESS',
  REMOVE_ONE_IMAGE_FROM_COLOR_IMAGES_FAILED: 'REMOVE_ONE_IMAGE_FROM_COLOR_IMAGES_FAILED',

}

export default ProductsActionTypes