enum UserActionTypes {
  SIGN_UP_REQUESTED = 'SIGN_UP_REQUESTED',
  SIGN_UP_FAILED = 'SIGN_UP_FAILED',

  EMAIL_SIGN_IN_REQUESTED = 'EMAIL_SIGN_IN_REQUESTED',
  GOOGLE_SIGN_IN_REQUESTED = 'GOOGLE_SIGN_IN_REQUESTED',
  SIGN_IN_FAILED = 'SIGN_IN_FAILED',
  
  SET_CURRENT_USER = 'SET_CURRENT_USER',
  SET_TOKEN = 'SET_TOKEN',
  TOGGLE_IS_UPSERT = 'TOGGLE_IS_UPSERT',

  SIGN_OUT_REQUESTED = 'SIGN_OUT_REQUESTED',
  SIGN_OUT_SUCCESS = 'SIGN_OUT_SUCCESS',
  SIGN_OUT_FAILED = 'SIGN_OUT_FAILED',

  SESSION_EXPIRED = 'SESSION_EXPIRED',
  NAVIGATE_AFTER_SESSION_EXPIRED = 'NAVIGATE_AFTER_SESSION_EXPIRED',

  FORGOT_PASSWORD_REQUESTED = 'FORGOT_PASSWORD_REQUESTED',
  FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS',
  FORGOT_PASSWORD_FAILED = 'FORGOT_PASSWORD_FAILED',

  RESET_PASSWORD_REQUESTED = 'RESET_PASSWORD_REQUESTED',
  RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS',
  RESET_PASSWORD_FAILED = 'RESET_PASSWORD_FAILED',

  GET_LOGGED_USER_PROFILE_REQUESTED = 'GET_LOGGED_USER_PROFILE_REQUESTED',
  GET_LOGGED_USER_PROFILE_FAILED = 'GET_LOGGED_USER_PROFILE_FAILED',

  EDIT_LOGGED_USER_REQUESTED = 'EDIT_LOGGED_USER_REQUESTED',
  EDIT_LOGGED_USER_FAILED = 'EDIT_LOGGED_USER_FAILED',

  CREATE_ADDRESS_REQUESTED = 'CREATE_ADDRESS_REQUESTED',
  EDIT_ADDRESS_REQUESTED = 'EDIT_ADDRESS_REQUESTED',
  DELETE_ADDRESS_REQUESTED = 'DELETE_ADDRESS_REQUESTED',
  
  DELETE_ACCOUNT_REQUESTED = 'DELETE_ACCOUNT_REQUESTED',
  DELETE_ACCOUNT_SUCCESS = 'DELETE_ACCOUNT_SUCCESS',
  DELETE_ACCOUNT_FAILED = 'DELETE_ACCOUNT_FAILED',

  RESET_ERROR_MESSAGES = 'RESET_ERROR_MESSAGES',

  ADMIN_GET_ALL_USERS_REQUESTED = 'ADMIN_GET_ALL_USERS_REQUESTED',
  ADMIN_GET_ALL_USERS_SUCCESS = 'ADMIN_GET_ALL_USERS_SUCCESS',
  ADMIN_GET_ALL_USERS_FAILED = 'ADMIN_GET_ALL_USERS_FAILED',

  ADMIN_GET_USER_BY_ID_REQUESTED = 'ADMIN_GET_USER_BY_ID_REQUESTED',
  ADMIN_GET_USER_BY_ID_SUCCESS = 'ADMIN_GET_USER_BY_ID_SUCCESS',
  ADMIN_GET_USER_BY_ID_FAILED = 'ADMIN_GET_USER_BY_ID_FAILED',

  ADMIN_EDIT_USER_BY_ID_REQUESTED = 'ADMIN_EDIT_USER_BY_ID_REQUESTED',
  ADMIN_EDIT_USER_BY_ID_SUCCESS = 'ADMIN_EDIT_USER_BY_ID_SUCCESS',
  ADMIN_EDIT_USER_BY_ID_FAILED = 'ADMIN_EDIT_USER_BY_ID_FAILED',

  ADMIN_DELETE_USER_BY_ID_REQUESTED = 'ADMIN_DELETE_USER_BY_ID_REQUESTED',
  ADMIN_DELETE_USER_BY_ID_SUCCESS = 'ADMIN_DELETE_USER_BY_ID_SUCCESS',
  ADMIN_DELETE_USER_BY_ID_FAILED = 'ADMIN_DELETE_USER_BY_ID_FAILED'

}

export default UserActionTypes