const UserActionTypes = {
  SET_CURRENT_USER: 'SET_CURRENT_USER',
  SET_TOKEN: 'SET_TOKEN',
  SIGN_IN_FAILURE: 'SIGN_IN_FAILURE',
  SIGN_OUT_SUCCESS: 'SIGN_OUT_SUCCESS',
  SIGN_OUT_FAILURE: 'SIGN_OUT_FAILURE',
  SIGN_UP_FAILURE: 'SIGN_UP_FAILURE',
  RESET_ERROR_MESSAGE: 'RESET_ERROR_MESSAGE',
  DELETE_ACCOUNT_SUCCESS: 'DELETE_ACCOUNT_SUCCESS'
}

export default UserActionTypes;