const CollectionsActionTypes = {
  FETCH_COLLECTIONS_REQUESTED: 'FETCH_COLLECTIONS_REQUESTED',
  FETCH_COLLECTIONS_SHORT_INFO_REQUESTED: 'FETCH_COLLECTIONS_SHORT_INFO_REQUESTED',
  FETCH_COLLECTIONS_SUCCESS: 'FETCH_COLLECTIONS_SUCCESS',
  FETCH_COLLECTIONS_FAILURE: 'FETCH_COLLECTIONS_FAILURE',

}

export default CollectionsActionTypes;