const OrdersActionTypes = {
  CREATE_ORDER_REQUESTED: 'CREATE_ORDER_REQUESTED',
  CREATE_ORDER_FAILED: 'CREATE_ORDER_FAILED',

  SET_ORDERS: 'SET_ORDERS',
  SET_SELECTED_ORDER: 'SET_SELECTED_ORDER',

  GET_ORDERS_REQUESTED: 'GET_ORDERS_REQUESTED',
  GET_ORDERS_FAILED: 'GET_ORDERS_FAILED',

  GET_ORDER_DETAILS_REQUESTED: 'GET_ORDER_DETAILS_REQUESTED',
  GET_ORDER_DETAILS_FAILED: 'GET_ORDER_DETAILS_FAILED',

  EDIT_ORDER_REQUESTED: 'EDIT_ORDER_REQUESTED',
  EDIT_ORDER_FAILED: 'EDIT_ORDER_FAILED'
}

export default OrdersActionTypes